### PR TITLE
Share on social media issue resolved

### LINKED ISSUE #2970: Broken Facebook Share Link
**Actual Behaviour**

The share on facebook link directs to an error page.

**Expected Behaviour**

The link should load to a post to share susi.ai

**Steps to reproduce it**

1.Open susi.ai
2.Login to your account
3.Go to settings->Share on social media.

**Screenshots of the issue**
**Error Page**
vv

**Would you like to work on the issue?**

Yes

### LINKED ISSUE #2971: Use react-share to implement share on social media
**Expected Behaviour**
Facebook,Twitter and LinkedIn share buttons can be easily imported from `react-share` library
and can be used to share on social media.
This can be done to share on social media in settings.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Dilshaad21**
Fixes #2971
Fixes #2970 

Changes: 
-This solves both the issues and now all the share links are implemented using share buttons in `react-share` library.

Demo Link: https://pr-2972-fossasia-susi-web-chat.surge.sh

Screenshots of the change:
bb

### CODE REVIEW

File: src/components/Settings/ShareOnSocialMedia.js [hunk 1]
```diff
@@ -1,163 +1,88 @@
...
-  initFacebookAPI();
-  const { raisedButtonStyle } = styles;
-  const { classes } = props;
+const TwitterShareButton = styled(_TwitterShareButton)`
+  ${commonIconStyle};
+`;
+
+const ShareOnSocialMedia = () => {
+  const shareUrl = 'https://susi.ai';
+  const title = 'Lets chat with susi, the open source personal assistant';
```
Comment (akshatnitd) [inline src/components/Settings/ShareOnSocialMedia.js]: Make it `Lets chat with SUSI.AI, the open source personal assistant`

Comment (Dilshaad21) [reply src/components/Settings/ShareOnSocialMedia.js]: @akshatnitd done changes
