### PR TITLE
fixed material tables

### LINKED ISSUE #3316: Invalid prop `actions[0]` supplied to `MaterialTable`
**Actual Behaviour**

an error Invalid prop `actions[0]` supplied to `MaterialTable` occurs 

**Screenshots of the issue**

Screenshot 2020-01-18 at 1 28 19 PM

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by anishagg17**
Fixes #3316

Changes:

turned each action to a function 

Reference Link : https://github.com/mbrn/material-table/issues/657#issuecomment-515088181

Demo Link: https://pr-3317-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

File: src/components/Admin/ListUser/index.js [hunk 1]
```diff
@@ -299,8 +299,8 @@ class ListUser extends Component {
               <TablePagination
                 rowsPerPageOptions={[50]}
                 colSpan={3}
-                count={totalUsers}
-                rowsPerPage={'50'}
+                count={totalUsers || 0}
```
Comment (anishagg17) [inline src/components/Admin/ListUser/index.js]: it raised an error count is required but value passed is undefined

**Comment by anishagg17** [comment]
All instances of material-tables  have been updated
