### PR TITLE
Fixed navigation bar for mobiles

### LINKED ISSUE #3449: Improving navigation bar in mobile view
**Actual Behaviour**

073D045C-6946-440D-BEBF-2692315D1CFE

3D7EF94E-8248-4F57-B96E-E933A9CF429F

**Expected Behaviour**

1. Padding between display pic and + icon needs to be reduced
2. Dashboard is already present in popper and can be removed in mobile view to free up space.
3. Chat with susi can be removed as it is occupying enough space and we already hve chatbubble on the page.

**Screenshots of the issue**

Posted above.

**Would you like to work on the issue?**

Working on it.

### LINKED ISSUE #3450: Drop-down misalignment
**Actual Behaviour**

491B27B7-6A0F-412B-A1C0-E9BBD7E18A79
4261057A-8A31-462B-AFE1-DBD57DDC3ECD
14C39F9C-AD7C-4CF0-BB75-61228D280204

**Expected Behaviour**
1. They must be aligned at same height
2. About-and-support menu goes out of the page. 

**Screenshots of the issue**
Attached above

**Would you like to work on the issue?**

Working on it.

### PR DESCRIPTION
**Pull request by tobehonest**
Fixes #3449 
Fixes #3450

Changes: 
1. Fixed about menu overflowing outside
2. Fixed drop down alignments.
3. Fixed navigation bar for mobiles. Now navigation bar on mobiles is less congested.

Demo Link: http://abcdabcd.surge.sh/

Screenshots of the change: 
Screenshot from 2020-02-11 15-23-32
Screenshot from 2020-02-11 15-23-34
Screenshot from 2020-02-11 15-27-29
Screenshot from 2020-02-11 15-27-34

### CODE REVIEW

**Comment by tobehonest** [comment]
@akshatnitd Please review this PR.

**Comment by tobehonest** [comment]
> Pls try solving a single issue per PR.
Yes. I will create two separate PR next time.

File: src/components/NavigationBar/index.js [hunk 1]
```diff
@@ -669,24 +669,30 @@ class NavigationBar extends Component {
...
-                    <ToolTip title="Dashboard">
-                      <IconButton
-                        color="inherit"
-                        onClick={() => history.push('/dashboard')}
-                        style={{ padding: '7px' }}
-                      >
-                        <Dashboard />
-                      </IconButton>
-                    </ToolTip>
+                    {!isMobileView(400) ? (
```
Comment (akshatnitd) [inline src/components/NavigationBar/index.js]: Can you store the value of `isMobileView(400)` in a variable and then use it at instances to avoid multiple function calls?

**Comment by tobehonest** [comment]
@akshatnitd I have made the requested changes. Please Re-review.

File: src/components/NavigationBar/index.js [hunk 2]
```diff
@@ -198,6 +198,7 @@ class NavigationBar extends Component {
       searchSelectWidth: this.getSelectMenuWidth(this.props.searchType),
       showSearchBar: !isMobileView(1000),
       rightContainer: true,
+      isMobile400: isMobileView(400),
```
Comment (akshatnitd) [inline src/components/NavigationBar/index.js]: No need to store it in state variable. Just declare a variable named `mobileView` inside render

Comment (tobehonest) [reply src/components/NavigationBar/index.js]: done.

File: src/components/NavigationBar/index.js [hunk 3]
```diff
@@ -384,6 +384,7 @@ class NavigationBar extends Component {
   };
 
   render() {
+    var isMobile400 = isMobileView(400);
```
Comment (akshatnitd) [inline src/components/NavigationBar/index.js]: Why `var`?

Comment (akshatnitd) [reply src/components/NavigationBar/index.js]: `const isMobile = isMobileView(400)`

**Comment by tobehonest** [comment]
> `isMobile400` is not a good name. Have already pointed out to use `isMobile` repeatedly. <

Corrected this one.
