### PR TITLE
Fix Category wise display of cards in mobile view

### LINKED ISSUE #2148: Fix Category wise display of cards in mobile view
**Actual Behaviour**
Currently the mobile view is broken with a lot of space between the heading and the cards.

**Expected Behaviour**
Fix the mobile view.

**Steps to reproduce it**
Click on any category from sidebar.
Open console. Click on any mobile layout. See error.

**Screenshots of the issue**
Screenshot 2019-05-29 at 8 59 48 AM

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2148 
Changes: Fix Category wise display of cards in mobile view

Demo Link: https://pr-2151-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot 2019-06-01 at 10 35 28 PM

### CODE REVIEW

File: src/components/cms/BrowseSkill/BrowseSkill.js [hunk 1]
```diff
@@ -809,41 +816,76 @@ class BrowseSkill extends React.Component {
...
+                        item
+                        sm={6}
+                        alignContent="flex-end"
+                        style={{ alignItems: isMobile ? 'center' : 'left' }}
+                      >
+                        {skills.length > 10 && (
+                          <div>
+                            <FormControl
+                              style={{
+                                width: isMobileView(350) ? '120px' : '145px',
```
Comment (akshatnitd) [inline src/components/cms/BrowseSkill/BrowseSkill.js]: Why does isMobileView take in a param. It should do so.

**Comment by fragm3** [comment]
@akshatnitd We can do one thing, for all CSS specific changes we can integrate them together with `styled components` and `rem` unit together

File: src/components/cms/BrowseSkill/BrowseSkill.js (hunk 1 above)
Comment (harsh-jindal) [reply src/components/cms/BrowseSkill/BrowseSkill.js]: @akshatnitd This was done because iphone 5 has 320px width while it works perfectly fine for all phones above 350px width.

**Comment by harsh-jindal** [comment]
@fragm3 Yup I think this can be done. But I guess the only problem would be if we have many components like many same divs with different styles we need to discuss on the nomenclature.

**Comment by akshatnitd** [comment]
@fragm3 Yes, ideally we should do that. We should use CSS to achieve responsiveness. Javascript APIs of innerWidth should be used only if we need some change in JS logic. Like maybe, replacing Checkbox with Radio button based on device.

**Comment by fragm3** [comment]
@akshatnitd @harsh-jindal yes exactly, that's where styled-components will help. We should go with styled components for mobile responsive(talking about its implementation in `FormControl`. For replacing prop related logic or any js related logic we can create a styled components for the same instead of innerWidth.

**Comment by mariobehling** [comment]
Looks good to me, but yes would be great to have the approach outlined above. @fragm3 Could you open an issue, please? 

@akshatnitd I think this can be merged as a step into the right direction, right?

**Comment by fragm3** [comment]
@akshatnitd what can be done for this PR, I will be working on fixing the BrowseSkill, skill by language, etc. https://github.com/fossasia/susi.ai/issues/2219

**Comment by harsh-jindal** [comment]
@akshatnitd Shall I make a seperate variable and call isMobileView(350) so i'll be calling it once ?

**Comment by harsh-jindal** [comment]
@akshatnitd Please review. I have made changes and now used css instead of isMobileView()
