### PR TITLE
Fix Cancel search in search bar

### LINKED ISSUE #2494: Cancel search not working
**Actual Behaviour**

When clicking on cancel icon on search not working.

**Expected Behaviour**

Cancel icon should work.

**Screenshots of the issue**

cross

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2494 

Changes: Added a onClose function.

Demo Link: https://pr-2632-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot 2019-07-18 at 2 48 25 PM

### CODE REVIEW

**Comment by harsh-jindal** [comment]
To test:
type something in the search bar 
click on close icon

**Comment by harsh-jindal** [comment]
@akshatnitd Fixed

File: src/components/NavigationBar/index.js [hunk 1]
```diff
@@ -187,6 +187,10 @@ class NavigationBar extends Component {
   };
 
   handleSearch = value => {
+    if (typeof value !== 'string') {
```
Comment (akshatnitd) [inline src/components/NavigationBar/index.js]: What is this check for?

Comment (akshatnitd) [reply src/components/NavigationBar/index.js]: Won't default param value work here?

Comment (harsh-jindal) [reply src/components/NavigationBar/index.js]: @akshatnitd When onClose function is called it sends an object to the this.handleSearch instead of sending an empty string.
