### PR TITLE
Fix Dashboard in mobile view

### LINKED ISSUE #2329: Fix Dashboard in mobile view
**Actual Behaviour**
Dashboard is not readable in mobile view.

**Expected Behaviour**
Fix it.

**Screenshots of the issue**
Screenshot 2019-06-19 at 10 40 45 AM

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2329 

Changes: Fixed Dashboard in mobile view
Demo Link: https://pr-2337-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot 2019-06-21 at 9 01 47 AM

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@akshatnitd @samagragupta Fixed.

**Comment by harsh-jindal** [comment]
@akshatnitd I don't have a skill that is used. So in My Analytics i don't see the graph.

**Comment by akshatnitd** [comment]
How do I help here?

**Comment by harsh-jindal** [comment]
@akshatnitd Fixed.

File: src/components/cms/Dashboard/MyAnalytics.js [hunk 1]
```diff
@@ -71,7 +78,9 @@ class MyAnalytics extends Component {
           <div>
             {skillUsageCount !== 0 && (
               <React.Fragment>
-                <SubTitle>Skill Usage Distribution</SubTitle>
+                <SubTitle marginLeft={'1.4rem'}>
```
Comment (samagragupta) [inline src/components/cms/Dashboard/MyAnalytics.js]: If want to use ` marginLeft={'1.4rem'}` then use `style={{ marginLeft: 1.4rem }}>`

Comment (harsh-jindal) [reply src/components/cms/Dashboard/MyAnalytics.js]: @samagragupta It is a shared component.

Comment (harsh-jindal) [reply src/components/cms/Dashboard/MyAnalytics.js]: @samagragupta Corrected it. Made it `margin-left` instead of `margin`. It is a shared component and we are getting rid of inline styles. So it's better to keep it scalable for the future.

File: src/components/shared/Typography.js [hunk 2]
```diff
@@ -8,6 +8,7 @@ export const Title = styled.h1`
 export const SubTitle = styled.p`
   font-weight: normal;
   font-size: ${props => (props.size ? props.size : '1.5rem')}
+  margin-left: ${props => (props.marginLeft ? props.marginLeft : '0rem')}
```
Comment (fragm3) [inline src/components/shared/Typography.js]: Make it: `margin-left: ${props => (props.marginLeft ? props.marginLeft + 'rem' : '0rem')}`

Comment (harsh-jindal) [reply src/components/shared/Typography.js]: @fragm3 Why is this change required ?

**Comment by harsh-jindal** [comment]
@samagragupta What issue?

**Comment by samagragupta** [comment]
@harsh-jindal When I click on the button, the dropdown button opens and the page goes up.

**Comment by harsh-jindal** [comment]
@samagragupta Doesn't happen for me.

**Comment by samagragupta** [comment]
w21

**Comment by harsh-jindal** [comment]
@samagragupta As this is not at priority, and can be fixed later. As this has to e fixed for all material ui menus.

**Comment by akshatnitd** [comment]
@harsh-jindal You have not yet worked on https://github.com/fossasia/susi.ai/pull/2337#pullrequestreview-252712942 comment. It should look like that in the mobile view. The label of the pie-chart is being cut in your PR.

File: src/components/shared/Typography.js (hunk 2 above)
Comment (fragm3) [reply src/components/shared/Typography.js]: @harsh-jindal when calling would be like: `<SubTitle marginLeft={1.4}>`, which is better than what we are doing right now.

**Comment by harsh-jindal** [comment]
@akshatnitd I tried searching on how to increase the label width but i didn't find anything. Plus I think this issue is present in the demo (http://recharts.org/en-US/examples/CustomActiveShapePieChart) too. Just if you increse the label width there too same issue occurs.

**Comment by fragm3** [comment]
Happened to me as well, that's why I set the min-width of the page in old PR of SkillPage.

File: src/components/shared/PieChartContainer.js [hunk 3]
```diff
@@ -132,6 +136,7 @@ class PieChartContainer extends Component {
               fill="#8884d8"
               onMouseEnter={this.onPieEnter}
               {...otherProps}
+              label={'hello'}
```
Comment (akshatnitd) [inline src/components/shared/PieChartContainer.js]: ?

Comment (harsh-jindal) [reply src/components/shared/PieChartContainer.js]: @akshatnitd @fragm3 Fixed. This was done while trying to debug the label issue. Will try to avoid things .

**Comment by harsh-jindal** [comment]
@samagragupta Fixed
