### PR TITLE
Load blog posts with paginated ajax calls

### LINKED ISSUE #3154: Pagination on blog page
**Actual Behaviour**

There is no pagination, the user has to scroll a lot.

**Expected Behaviour**

There should be pagination if there are blogs more than a certain limit

**Steps to reproduce it**

Open https://susi.ai/blog

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by kumuditha-udayanga**
Fixes #3154 #3179 

Changes: 
- Add navigation buttons.
- Render data using paginated ajax calls.

Demo Link: https://pr-3174-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by kumuditha-udayanga** [comment]
@samagragupta @akshatnitd @mariobehling  It would be nice to have your reviews :)

**Comment by anishagg17** [comment]
I don't think there is any need for pagination in blog section

**Comment by kumuditha-udayanga** [comment]
> I don't think there is any need for pagination in the blog section
@anishagg17  Read this issue #3179. Thank you

**Comment by jayasanka-sack** [comment]
@anishagg17 I've also identified this issue (#3179). It takes a long loading time to receive a payload with 50 posts. And the count `50` is hardcoded, which is not a good practice. I went through this PR and saw he had paginated the feed request too. And also, there are navigation buttons that navigate to the next blog posts. Hence, I think this change is useful.

+1 from me. 😇

PS:
@kumuditha-udayanga Looks there are some conflicts with the latest merge. Please resolve them.

**Comment by kumuditha-udayanga** [comment]
@mariobehling Please review and merge :)

**Comment by anishagg17** [comment]
yep bro , you are right pagination should be there 😇

But there is an issue too
pagination is not disabled at last page instead it's disabled on (last+1) th page.
Also i think the buttons used for pagination are not good .You may refer to the pagination in my ratings section to see the UI
You may see this:
Screenshot 2019-12-31 at 6 10 18 PM

**Comment by anishagg17** [comment]
yep bro , you are right pagination should be there 😇

**Comment by kpulkit29** [comment]
@kumuditha-udayanga I was already working on #3154 . You opened a duplicate issue and started working on it without even confirming if someone else is on it. I am pointing this out because two people working on the same thing independently does not make any sense. I was half way through my solution and then you created a duplicate issue. You should respect the open source contribution guidelines. Since you have raised the PR without asking my time and effort is clearly wasted here.
@akshatnitd @mariobehling would like to know your thoughts here as I was working on #3154 and @kumuditha-udayanga opened a sort of duplicate issue #3179 .

**Comment by Dilshaad21** [comment]
@kumuditha-udayanga I suppose that you are a first time contributor, so please now onwards ask for the issue and if accepted then only start working on the issue. Thanks

**Comment by kumuditha-udayanga** [comment]
> @kumuditha-udayanga I suppose that you are a first time contributor, so please now onwards ask for the issue and if accepted then only start working on the issue. Thanks

Yes I am, and I am new to GitHub and contributing

**Comment by kpulkit29** [comment]
@Dilshaad21  I had also started with the coding part. I wanted to raise a PR as well. What do you suggest should be done now since I opened the issue first?

**Comment by Dilshaad21** [comment]
@kumuditha-udayanga I understand that. You can take some other issues which are free for pick. So you need to kindly close this PR as it's mistake from your side. And make sure you follow the contribution guidelines in the future.

**Comment by kumuditha-udayanga** [comment]
@Dilshaad21 @kpulkit29 Pardon me.

By the way, 
the #3179 issue is a different one. When I see the ajax call I saw there are 50 blog posts are getting from the blog feed. And the value 50 is hardcoded in the code. It takes a big time to fetch 50 posts from the blog feed. That was the issue I tried to solve. So, what my solution was to add a limit and offset to API call and get 10 posts from the API at a time. Which saves resources. When I'm working on this issue, #3154 also automatically solved. But that is not the change I was working on. Because of that only I've referred it to my PR.
I suggest that my PR title should change to "Load blog posts with paginated ajax calls" 

Additionally, the pagination is already implemented in the current code. The only issue is that buttons were hidden with CSS mistakenly. Removing that line will solve #3154. 

@kpulkit29 You can work on #3154 and send your PR. After your PR merged, I will resolve conflicts and Put this PR to fix #3179. I think it will solve this issue. Sorry for my mistake.
Thanks for understanding.

**Comment by kpulkit29** [comment]
@kumuditha-udayanga I understand your point now.

**Comment by kpulkit29** [comment]
Kindly change your PR title

File: src/components/About/Blog/index.js [hunk 1]
```diff
@@ -199,29 +198,47 @@ class Blog extends Component {
...
+        nextDisplay = 'hidden';
+      }
+      if (offset === 0) {
+        prevDisplay = 'hidden';
+      }
+      this.setState({
+        posts: payload.items,
+        postRendered: true,
+        startPage: offset,
+        nextDisplay: nextDisplay,
```
Comment (akshatnitd) [inline src/components/About/Blog/index.js]:
```
nextDisplay: postsCount < 10 ? 'hidden' : 'visible',
prevDisplay: offset === 0 ? 'hidden' : 'visible',
```

Use this, it will reduce lines of code.

**Comment by kumuditha-udayanga** [comment]
@akshatnitd The changes have been done :)
