### PR TITLE
Fixed the alignment of social profile icons

### LINKED ISSUE #3321: Adjust the social profiles buttons
**Actual Behaviour**
The social profile buttons aren't responsive with the page.

**Expected Behaviour**
The social profile icons should adjust their alignment as and when the page resolution changes.

**Steps to reproduce it**
- Go to the `Share On the Social Media` option in settings and tune the screen resolutions.

**Screenshots of the issue**
Screenshot from 2020-01-18 21-47-30

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Dishebh**
Fixes #3321 

Changes: Made the social profile icons responsive with the web page

Demo Link: https://pr-3323-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot from 2020-01-18 22-33-49

### CODE REVIEW

File: src/components/Settings/ShareOnSocialMedia.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ const commonIconStyle = css`
 `;
 
 const ShareIconContainer = styled.div`
-  display: flex;
+  display: flow-root;
```
Comment (akshatnitd) [inline src/components/Settings/ShareOnSocialMedia.js]: Use flex-wrap, `flow-root` is not supported by all browsers.

Comment (Dishebh) [reply src/components/Settings/ShareOnSocialMedia.js]: Done

**Comment by Dishebh** [comment]
@akshatnitd pls merge. Thanks!
