### PR TITLE
High resolution content disappearing bug fix (fossasia#3519)

### LINKED ISSUE #3519: Start Page Content area and menu disappear on a number of browsers on larges screens
Screenshot from 2020-05-03 15-32-48

After an initial loading time the start page content in the main area disappears as shown in the screenshot on large screens with a resolution wider than 2560px.

### PR DESCRIPTION
**Pull request by ashutoshc8101**
### Fixes #3519
Content disappering on resolution > 2400px is fixed with this PR.

##### Changes: 
- Content at home page which used to disappear at width > 2400px doesn't disappear now.

#### What was wrong?
- Width of right container on home page was only defined upto 2400px.

- Due to lack of specified width for screens > 2400px, the right container div gets automatically enlarged.

- Which results in disappearing of content for the user.

#### What I did?
- I removed the media queries specifying different widths for different screen sizes.
- Instead I used relative width for sidebar(15%) and right container(85%) with flexbox .
- Now the width changes properly with different screen sizes.

Before:
At 2401px:
before
At 4000px:
Screenshot from 2020-12-19 15-17-29

Now:
At 2401px:
Screenshot from 2020-12-19 15-18-03
At 4000px:
Screenshot from 2020-12-19 15-18-18

Demo Link: https://pr-3621-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by ashutoshc8101** [comment]
@akshatnitd Please review

**Review by Dilshaad21 — APPROVED** [review]
Looks good to me :+1:

**Comment by ashutoshc8101** [comment]
@Dilshaad21 I fixed that. Now right toggle button disappears when required.

File: src/components/cms/SkillCardScrollList/SkillCard.js [hunk 1]
```diff
@@ -74,12 +74,31 @@ class SkillCard extends Component {
...
+        scrollCards = 9;
+        break;
+      case window.innerWidth >= 2700:
+        scrollCards = 8;
+        break;
+      case window.innerWidth >= 2400:
+        scrollCards = 7;
+        break;
+      case window.innerWidth >= 2100:
+        scrollCards = 6;
```
Comment (Dilshaad21) [inline src/components/cms/SkillCardScrollList/SkillCard.js:100]: Try to make these `window.innerWidth` conditions consistent with the previous ones. As the skillcard size is around 180px.

**Review by Dilshaad21 — CHANGES_REQUESTED** [review]

File: src/components/cms/SkillCardScrollList/SkillCard.js (hunk 1 above)
Comment (ashutoshc8101) [reply src/components/cms/SkillCardScrollList/SkillCard.js:100]: Sir, the skillcard size is 280px. We cannot add 280px straight to 840 because i have used relative width for sidebar. When I am adding 280px, the right arrow is getting misaligned with the cards.
I have given width = 15% for the sidebar.
So, I am using the formula `window.innerWidth * 0.15 + 10px[Margin to Sidebar] + 280px[Box size]*n[number of boxes to display]` formula to get the required width for switch statements.
As this formula calculates it value from n, therefore i replaced switch with a for loop.


Now I am gettings desired result in the webpage

**Comment by ashutoshc8101** [comment]
@Dilshaad21 
As width of sidebar is relative. I have now replaced  `window.innerWidth` static conditions in switch with a formula.
Formula calculates width conditions using ` window.innerWidth * 0.15 + 19px[Margin to Sidebar] + 280px[Box size]*n[number of boxes to display] `

I have given 15% width to sidebar, therefore, I am multiplying window.innerWidth with 0.15

As this formula depends on n. So, I have used a reverse for loop in place of switch.
Finally, I squashed the commits.

File: src/components/cms/SkillCardScrollList/SkillCard.js [hunk 2]
```diff
@@ -74,27 +74,22 @@ class SkillCard extends Component {
...
-        break;
-      case window.innerWidth >= 1120:
-        scrollCards = 3;
-        break;
-      case window.innerWidth >= 840:
-        scrollCards = 2;
+    // Correct positioning of Right arrow for SkillCards upto 20 is supported with this for loop.
+    const MAX_CARDS_SUPPORT = 20;
+    for (let i = MAX_CARDS_SUPPORT; i > 1; i--) {
+      if (window.innerWidth >= window.innerWidth * 0.15 + 19 + i * 280) {
```
Comment (akshatnitd) [inline src/components/cms/SkillCardScrollList/SkillCard.js:89]: Can you add appropriate comments to explain the formula?

Comment (ashutoshc8101) [reply src/components/cms/SkillCardScrollList/SkillCard.js:107]: @akshatnitd Comments explaining formula added.

**Review by Dilshaad21 — APPROVED** [review]
LGTM

**Comment by ashutoshc8101** [comment]
@akshatnitd Please Review

**Review by akshatnitd — APPROVED** [review]
LGTM 🚀
