### PR TITLE
Improve Dashboard Conformity across pages and fix minor bugs

### LINKED ISSUE #2578: Improve Dashboard Conformity across pages
* Dashboard page link "Create Skill" button to create skills only (not bots!)
* On My Skills page (https://susi.ai/myskills) 
   * change headings to H1 and 
   * move "Create a new skills" to the end of the list.
* On My Bots page (https://susi.ai/mybots):
  * take out "My Bots" heading (it is repetitive)
  * change other headings to H1
   * move "Create a new bot" to the end of the list.
* On all pages decrease gray area padding below secondary menu
Screenshot from 2019-07-15 22-17-24

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2578, #2682
Changes: Added loader in My Bots and made the specified changes in the issue.
Added missing heading `Share about SUSI` and increased the message composer font-size to 1rem.

Demo Link: https://pr-2683-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot 2019-07-27 at 11 30 46 AM

### CODE REVIEW

File: src/components/Settings/ShareOnSocialMedia.js [hunk 1]
```diff
@@ -86,7 +86,7 @@ const ShareOnSocialMedia = props => {
   const { raisedButtonStyle } = styles;
   const { classes } = props;
   return (
-    <SettingsTabWrapper heading="">
+    <SettingsTabWrapper heading="Share about SUSI">
```
Comment (akshatnitd) [inline src/components/Settings/ShareOnSocialMedia.js]: `SUSI.AI`

File: src/components/cms/SkillCreator/SkillCreator.js [hunk 2]
```diff
@@ -186,13 +196,14 @@ class SkillCreator extends Component {
     return (
       <Container>
         <Paper>
-          {showTitle && <h1>My Skills</h1>}
-          <br />
-          <h2>Created Skills</h2>
+          {showTitle && <H1>My Skills</H1>}
```
Comment (akshatnitd) [inline src/components/cms/SkillCreator/SkillCreator.js]: Why not write `<br />` inside `<H1>`?

**Comment by harsh-jindal** [comment]
@akshatnitd Fixed.
