### PR TITLE
Removed unnecessary choose button and fixed the bug when avatar image is removed

### LINKED ISSUE #2481: Remove choose file button
**Actual Behaviour**

Unnecessary `choose file` button is present in settings.

**Expected Behaviour**

Remove `choose file` button from settings->account

**Screenshots of the issue**
Capture

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #2481

Changes: 
- Removed `choose file` button from settings->account
- fixed the bug when avatar image is removed

Demo Link: https://pr-2503-fossasia-susi-web-chat.surge.sh

Capture

### CODE REVIEW

**Comment by samagragupta** [comment]
@fragm3 Fixed that

File: src/components/Settings/Avatar.js [hunk 1]
```diff
@@ -19,6 +19,10 @@ const Fab = styled(_Fab)`
   left: 4%;
 `;
 
+const AvataInput = styled.input`
```
Comment (harsh-jindal) [inline src/components/Settings/Avatar.js]: Rename this to `AvatarInput`

Comment (samagragupta) [reply src/components/Settings/Avatar.js]: Done
